dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
install:
  - pip install tox pipenv
  - pipenv install
script: tox
deploy:
  provider: pypi
  user: jacobi
  skip_existing: true
  on:
    branch: master
    tags: true
