dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
install:
  - pip install tox pipenv
  - pipenv install --dev
script:
  - tox
  - archives gamble/
deploy:
  provider: pypi
  user: jacobi
  skip_existing: true
  on:
    branch: master
    tags: true
  password:
    secure: XaZWWSz0QOmCvh5mhyrJcbKYQ25HMzdgc+tIFDEhGIPX77D+Oa9T+qThQn1268WgJeQNLGc1kiR3DauoVN1BNJeUoyXyvpdytvndnQmrj3+7abjSaOtPPrFU0rlB9tOrUs/tb1maaY0f38TlElbdWPGC6T7M7JQ9j9CmZ734bPpBrImDNMnYJ7IUHG+9OVY8PJanih1ss3TGk7tZ+FbS9ojC2CayyQsfcMsrQwJLcSUiCbeu209JX3G9QgwDs+BegrGsX170UaibS438CcXJa05zGH7irW5ooQj3inEHAevJIlpdZN+A+terqtwdghDs7tX/cVxReeeWsavOusxxK5mjQkB0shMTWQ2NBCXAheHsyGt2Kd+vZ7Ro81xMbmHnGKQtGzu5AKR4vV7MUWzNeGGPqUYttiHCk8u3aGf+iAbrEJMS9+oYT8hgsBNdyWu7uBjkjG+ugbFpDA0mJj54omYlJv0tuPW25JUpEppk3gvNaZAX6RVGr3kNzXsJjxwNyFKm/Z0fG9IgkPnNPOT0bp3sN9/uIkGZKCacUyun+yRlqLeqdBRPGhmDKNj668/9fgs388idqf1Z5LxKBMJGsO4GVAB/2esNrAKh1wvN9quEEgZyTFXOZ/nxtiUHjgbXD8hmQHx20G5/kaLAiO1Y3ST5d5B9F71ef9FoJSR31N0=
